#!/bin/sh
#
# This script is a sort of pre-processor for LaTeX
# The second argument is a filename suffix
# It appends the 3nd argument to the arguments for the document class
#
# It's useful in conjunction with makefiles for building drafts or,
# in the case of beamer, separate slides and notes, without changing
# the source file.
# e.g. lcls input.latex input-draft.latex "draft,12pt"
# This will create a input-draft.latex file with 'draft,12pt' added to
# the document class options, written to input-draft.latex
#
# This code does not check for other running latex systems, and will
# overwrite other source files if misused.
# There is one further caveat in that, as this is implemented as as
# type-3 grammar script, type-2 language features can cause issues.
# In English, this means that nesting [] in the document class option
# list will cause the injection to happen in the wrong place.
#
# Written By: Benedict Harcourt <ben.harcourt@harcourtprogramming.co.uk>
# Last Modified: 13/11/2011
# Released Under Creative Commons Attribution 3.0 Unported License

if [ "$#" -lt 2 ]; then
	printf "Usage: ${0##*/} source target [extra class arguments]\n"
	exit 1
fi

if [ ! -r "$1" ]; then
	printf "Fatal: Unable to read source file $1\n"
	exit 2
fi

if [ -n "$3" ]; then
	sed -e "s/\\documentclass\[\(.*\)]/\documentclass[\1,$3]/" "$1" > "$2"
else
	cp "$1" "$2"
fi

